Component has fully qualified name saved in database
tomaslestyan/sonar_measurements_framework pull request #19
Opened 2017-05-17 15:36 UTC by kerleba

2017-05-17 19:43 UTC, tomaslestyan requested changes

2017-05-17 19:43 UTC, tomaslestyan commented on framework/src/main/java/framework/visitors/java/FileVisitor.java
> +					packageName, null, null, Collections.emptyList(), tree.firstToken().line(), tree.lastToken().line());
zatial to nie je sice potreba, ale mohlo by sa to ukladat aj pre metodu nie?

2017-05-17 20:09 UTC, kerleba commented on framework/src/main/java/framework/visitors/java/FileVisitor.java
> +					packageName, null, null, Collections.emptyList(), tree.firstToken().line(), tree.lastToken().line());
Je nějak definované FQN pro metodu?

2017-05-17 21:12 UTC, tomaslestyan commented on framework/src/main/java/framework/visitors/java/FileVisitor.java
> +					packageName, null, null, Collections.emptyList(), tree.firstToken().line(), tree.lastToken().line());
nasiel som toto: com.sun.map.imap.IMAPFolder.addMessages(Message[] msgs), ale podla mna stacia len typy parametrov, co bude tazke, takze by som navrhoval com.sun.map.imap.IMAPFolder.addMessages(msgs)

2017-05-18 15:34 UTC, kerleba commented on framework/src/main/java/framework/visitors/java/FileVisitor.java
> +					packageName, null, null, Collections.emptyList(), tree.firstToken().line(), tree.lastToken().line());
Upřímně se mi to nechce dělat, když to teď nikdo z nás nevyužije.

2017-05-18 16:27 UTC, tomaslestyan commented on framework/src/main/java/framework/visitors/java/FileVisitor.java
> +					packageName, null, null, Collections.emptyList(), tree.firstToken().line(), tree.lastToken().line());
Ok, davam approve

2017-05-18 16:27 UTC, tomaslestyan approved these changes

2017-05-18 16:39 UTC, merged